on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Up Python3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry export -f requirements.txt --output requirements.txt
        pip install -r requirements.txt
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint sockets_framework/ --load-plugins=pylint_django --django-settings-module=core.settings --max-line-length=88 --disable --notes=
    - name: Publish
      run: |
        poetry publish --username anatolio --password ad.5319.93A
